version: '3.8'

services:
  rag-backend:
    build:
      context: .
    container_name: rag-backend
    env_file:
      - .env
    ports:
      - "8001:8001"
    environment:
      - QDRANT_HOST=${QDRANT_HOST}
    restart: unless-stopped
